[package]
name = "ac2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
